// @generated by proto/codegen.ts from proto/mtp.schema.json — DO NOT EDIT.

import Foundation

public struct ProtoRange: Codable, Sendable {
    public var min: Int
    public var max: Int

    public init(min: Int, max: Int) {
        self.min = min
        self.max = max
    }

    enum CodingKeys: String, CodingKey {
        case min = "min"
        case max = "max"
    }
}

public enum Role: String, Codable, Sendable {
    case host = "host"
    case client = "client"
    case provider = "provider"
    case agent = "agent"
}

public enum Capability: String, Codable, Sendable {
    case coreBasic = "core.basic"
    case terminalControl = "terminal.control"
    case terminalIo = "terminal.io"
    case terminalContextRead = "terminal.context.read"
    case terminalContextWrite = "terminal.context.write"
    case agentStateRead = "agent.state.read"
    case agentStateWrite = "agent.state.write"
    case sessionBind = "session.bind"
    case actionInvoke = "action.invoke"
    case attentionNotify = "attention.notify"
    case uiHost = "ui.host"
    case providerQuickOpen = "provider.quickOpen"
    case providerDetailsView = "provider.detailsView"
    case providerBadge = "provider.badge"
    case providerAction = "provider.action"
}

public struct Limits: Codable, Sendable {
    public var maxMessageBytes: Int
    public var ratePerSec: Int
    public var idleTimeoutMs: Int

    public init(maxMessageBytes: Int, ratePerSec: Int, idleTimeoutMs: Int) {
        self.maxMessageBytes = maxMessageBytes
        self.ratePerSec = ratePerSec
        self.idleTimeoutMs = idleTimeoutMs
    }

    enum CodingKeys: String, CodingKey {
        case maxMessageBytes = "max_message_bytes"
        case ratePerSec = "rate_per_sec"
        case idleTimeoutMs = "idle_timeout_ms"
    }
}

public struct HelloParams: Codable, Sendable {
    public var proto: ProtoRange
    public var appVersion: String
    public var roles: [Role]
    public var caps: [Capability]
    public var clientId: String

    public init(proto: ProtoRange, appVersion: String, roles: [Role], caps: [Capability], clientId: String) {
        self.proto = proto
        self.appVersion = appVersion
        self.roles = roles
        self.caps = caps
        self.clientId = clientId
    }

    enum CodingKeys: String, CodingKey {
        case proto = "proto"
        case appVersion = "app_version"
        case roles = "roles"
        case caps = "caps"
        case clientId = "client_id"
    }
}

public struct WelcomeParams: Codable, Sendable {
    public var proto: Int
    public var session: String
    public var caps: [Capability]
    public var limits: Limits
    public var revision: Int

    public init(proto: Int, session: String, caps: [Capability], limits: Limits, revision: Int) {
        self.proto = proto
        self.session = session
        self.caps = caps
        self.limits = limits
        self.revision = revision
    }

    enum CodingKeys: String, CodingKey {
        case proto = "proto"
        case session = "session"
        case caps = "caps"
        case limits = "limits"
        case revision = "revision"
    }
}

public struct ErrorInfo: Codable, Sendable {
    public var code: String
    public var message: String
    public var retryable: Bool
    public var details: AnyCodable?

    public init(code: String, message: String, retryable: Bool, details: AnyCodable? = nil) {
        self.code = code
        self.message = message
        self.retryable = retryable
        self.details = details
    }

    enum CodingKeys: String, CodingKey {
        case code = "code"
        case message = "message"
        case retryable = "retryable"
        case details = "details"
    }
}

public struct Request: Codable, Sendable {
    public var v: Int
    public var id: Int
    public var kind: String
    public var ns: String
    public var method: String
    public var params: AnyCodable?
    public var role: Role?
    public var caps: [Capability]?
    public var ts: Int?
    public var trace: String?

    public init(v: Int, id: Int, kind: String, ns: String, method: String, params: AnyCodable? = nil, role: Role? = nil, caps: [Capability]? = nil, ts: Int? = nil, trace: String? = nil) {
        self.v = v
        self.id = id
        self.kind = kind
        self.ns = ns
        self.method = method
        self.params = params
        self.role = role
        self.caps = caps
        self.ts = ts
        self.trace = trace
    }

    enum CodingKeys: String, CodingKey {
        case v = "v"
        case id = "id"
        case kind = "kind"
        case ns = "ns"
        case method = "method"
        case params = "params"
        case role = "role"
        case caps = "caps"
        case ts = "ts"
        case trace = "trace"
    }
}

public struct Response: Codable, Sendable {
    public var v: Int
    public var id: Int
    public var kind: String
    public var ok: Bool
    public var result: AnyCodable?
    public var error: ErrorInfo?
    public var revision: Int?

    public init(v: Int, id: Int, kind: String, ok: Bool, result: AnyCodable? = nil, error: ErrorInfo? = nil, revision: Int? = nil) {
        self.v = v
        self.id = id
        self.kind = kind
        self.ok = ok
        self.result = result
        self.error = error
        self.revision = revision
    }

    enum CodingKeys: String, CodingKey {
        case v = "v"
        case id = "id"
        case kind = "kind"
        case ok = "ok"
        case result = "result"
        case error = "error"
        case revision = "revision"
    }
}

public struct Event: Codable, Sendable {
    public var v: Int
    public var kind: String
    public var ns: String
    public var event: String
    public var data: AnyCodable?
    public var seq: Int?
    public var replayable: Bool?

    public init(v: Int, kind: String, ns: String, event: String, data: AnyCodable? = nil, seq: Int? = nil, replayable: Bool? = nil) {
        self.v = v
        self.kind = kind
        self.ns = ns
        self.event = event
        self.data = data
        self.seq = seq
        self.replayable = replayable
    }

    enum CodingKeys: String, CodingKey {
        case v = "v"
        case kind = "kind"
        case ns = "ns"
        case event = "event"
        case data = "data"
        case seq = "seq"
        case replayable = "replayable"
    }
}

public enum AgentState: String, Codable, Sendable {
    case processing = "processing"
    case idle = "idle"
    case awaiting = "awaiting"
    case error = "error"
}

public struct AgentStateSetParams: Codable, Sendable {
    public var agent: String
    public var sessionId: String?
    public var paneId: String?
    public var tty: String?
    public var agentPid: Int?
    public var state: AgentState
    public var cwd: String?
    public var bypass: Bool?
    public var errorKind: String?
    public var title: String?
    public var ts: Int?

    public init(agent: String, sessionId: String? = nil, paneId: String? = nil, tty: String? = nil, agentPid: Int? = nil, state: AgentState, cwd: String? = nil, bypass: Bool? = nil, errorKind: String? = nil, title: String? = nil, ts: Int? = nil) {
        self.agent = agent
        self.sessionId = sessionId
        self.paneId = paneId
        self.tty = tty
        self.agentPid = agentPid
        self.state = state
        self.cwd = cwd
        self.bypass = bypass
        self.errorKind = errorKind
        self.title = title
        self.ts = ts
    }

    enum CodingKeys: String, CodingKey {
        case agent = "agent"
        case sessionId = "session_id"
        case paneId = "pane_id"
        case tty = "tty"
        case agentPid = "agent_pid"
        case state = "state"
        case cwd = "cwd"
        case bypass = "bypass"
        case errorKind = "error_kind"
        case title = "title"
        case ts = "ts"
    }
}

public struct AgentStateInfo: Codable, Sendable {
    public var agent: String
    public var sessionId: String?
    public var paneId: String?
    public var state: AgentState
    public var cwd: String?
    public var bypass: Bool?
    public var errorKind: String?
    public var title: String?
    public var ts: Int?
    public var seq: Int?

    public init(agent: String, sessionId: String? = nil, paneId: String? = nil, state: AgentState, cwd: String? = nil, bypass: Bool? = nil, errorKind: String? = nil, title: String? = nil, ts: Int? = nil, seq: Int? = nil) {
        self.agent = agent
        self.sessionId = sessionId
        self.paneId = paneId
        self.state = state
        self.cwd = cwd
        self.bypass = bypass
        self.errorKind = errorKind
        self.title = title
        self.ts = ts
        self.seq = seq
    }

    enum CodingKeys: String, CodingKey {
        case agent = "agent"
        case sessionId = "session_id"
        case paneId = "pane_id"
        case state = "state"
        case cwd = "cwd"
        case bypass = "bypass"
        case errorKind = "error_kind"
        case title = "title"
        case ts = "ts"
        case seq = "seq"
    }
}

public struct AgentStateListResult: Codable, Sendable {
    public var revision: Int
    public var states: [AgentStateInfo]

    public init(revision: Int, states: [AgentStateInfo]) {
        self.revision = revision
        self.states = states
    }

    enum CodingKeys: String, CodingKey {
        case revision = "revision"
        case states = "states"
    }
}

public struct PingResult: Codable, Sendable {
    public var proto: Int
    public var appVersion: String
    public var pid: Int
    public var caps: [Capability]

    public init(proto: Int, appVersion: String, pid: Int, caps: [Capability]) {
        self.proto = proto
        self.appVersion = appVersion
        self.pid = pid
        self.caps = caps
    }

    enum CodingKeys: String, CodingKey {
        case proto = "proto"
        case appVersion = "app_version"
        case pid = "pid"
        case caps = "caps"
    }
}

public struct HealthResult: Codable, Sendable {
    public var ok: Bool
    public var revision: Int
    public var connections: Int?
    public var eventsPerSec: Double?
    public var droppedEvents: Int?

    public init(ok: Bool, revision: Int, connections: Int? = nil, eventsPerSec: Double? = nil, droppedEvents: Int? = nil) {
        self.ok = ok
        self.revision = revision
        self.connections = connections
        self.eventsPerSec = eventsPerSec
        self.droppedEvents = droppedEvents
    }

    enum CodingKeys: String, CodingKey {
        case ok = "ok"
        case revision = "revision"
        case connections = "connections"
        case eventsPerSec = "events_per_sec"
        case droppedEvents = "dropped_events"
    }
}

public struct Selection: Codable, Sendable {
    public var text: String
    public var startLine: Int?
    public var endLine: Int?

    public init(text: String, startLine: Int? = nil, endLine: Int? = nil) {
        self.text = text
        self.startLine = startLine
        self.endLine = endLine
    }

    enum CodingKeys: String, CodingKey {
        case text = "text"
        case startLine = "start_line"
        case endLine = "end_line"
    }
}

public struct GitInfo: Codable, Sendable {
    public var branch: String
    public var dirty: Bool
    public var worktree: String?

    public init(branch: String, dirty: Bool, worktree: String? = nil) {
        self.branch = branch
        self.dirty = dirty
        self.worktree = worktree
    }

    enum CodingKeys: String, CodingKey {
        case branch = "branch"
        case dirty = "dirty"
        case worktree = "worktree"
    }
}

public struct OpenFile: Codable, Sendable {
    public var path: String
    public var line: Int?
    public var readonly: Bool?

    public init(path: String, line: Int? = nil, readonly: Bool? = nil) {
        self.path = path
        self.line = line
        self.readonly = readonly
    }

    enum CodingKeys: String, CodingKey {
        case path = "path"
        case line = "line"
        case readonly = "readonly"
    }
}

public struct ContextSnapshot: Codable, Sendable {
    public var paneId: String
    public var cwd: String?
    public var shell: String?
    public var title: String?
    public var running: String?
    public var selection: Selection?
    public var screenTail: String?
    public var scrollbackTail: String?
    public var git: GitInfo?
    public var openFile: OpenFile?
    public var agent: AgentStateInfo?

    public init(paneId: String, cwd: String? = nil, shell: String? = nil, title: String? = nil, running: String? = nil, selection: Selection? = nil, screenTail: String? = nil, scrollbackTail: String? = nil, git: GitInfo? = nil, openFile: OpenFile? = nil, agent: AgentStateInfo? = nil) {
        self.paneId = paneId
        self.cwd = cwd
        self.shell = shell
        self.title = title
        self.running = running
        self.selection = selection
        self.screenTail = screenTail
        self.scrollbackTail = scrollbackTail
        self.git = git
        self.openFile = openFile
        self.agent = agent
    }

    enum CodingKeys: String, CodingKey {
        case paneId = "pane_id"
        case cwd = "cwd"
        case shell = "shell"
        case title = "title"
        case running = "running"
        case selection = "selection"
        case screenTail = "screen_tail"
        case scrollbackTail = "scrollback_tail"
        case git = "git"
        case openFile = "open_file"
        case agent = "agent"
    }
}

public struct ActionInfo: Codable, Sendable {
    public var id: String
    public var title: String
    public var namespace: String?

    public init(id: String, title: String, namespace: String? = nil) {
        self.id = id
        self.title = title
        self.namespace = namespace
    }

    enum CodingKeys: String, CodingKey {
        case id = "id"
        case title = "title"
        case namespace = "namespace"
    }
}

public struct ActionInvokeParams: Codable, Sendable {
    public var id: String
    public var args: AnyCodable?
    public var paneId: String?

    public init(id: String, args: AnyCodable? = nil, paneId: String? = nil) {
        self.id = id
        self.args = args
        self.paneId = paneId
    }

    enum CodingKeys: String, CodingKey {
        case id = "id"
        case args = "args"
        case paneId = "pane_id"
    }
}
