#!/usr/bin/env bun
/**
 * MTP codegen — proto/mtp.schema.json is the single source of truth.
 *
 * Emits:
 *   cli/crates/mtp/src/types.rs                              (Rust / serde)
 *   macos/MiaottyKit/Sources/MiaottyKit/MTP/Types.swift      (Swift / Codable)
 *   plugin/src/protocol.ts                                   (TypeScript)
 *
 * Supported schema subset: object, string, integer, number, boolean, array,
 * $ref, string enum, and free-form objects (additionalProperties: true).
 * Run: bun proto/codegen.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const schema = JSON.parse(readFileSync(join(import.meta.dir, "mtp.schema.json"), "utf8"));
const defs: Record<string, any> = schema.$defs ?? {};

const BANNER = `// @generated by proto/codegen.ts from proto/mtp.schema.json — DO NOT EDIT.`;

type Ref = { ref: string };
type Arr = { array: Ty };
type Ty = "string" | "integer" | "number" | "boolean" | "freemap" | Ref | Arr;

const isRef = (t: Ty): t is Ref => typeof t === "object" && "ref" in t;
const isArr = (t: Ty): t is Arr => typeof t === "object" && "array" in t;

function mapType(prop: any): Ty {
  if (!prop) return "freemap";
  if (prop.$ref) return { ref: String(prop.$ref).split("/").pop()! };
  if (prop.const !== undefined) {
    const v = prop.const;
    return typeof v === "boolean" ? "boolean" : typeof v === "number" ? "number" : "string";
  }
  switch (prop.type) {
    case "string":
      return "string";
    case "integer":
      return "integer";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return { array: mapType(prop.items) };
    case "object":
      return "freemap";
    default:
      return "freemap";
  }
}

const snakeToCamel = (s: string) =>
  s.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase()).replace(/^_/, "");
const pascal = (s: string) =>
  s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("") || "Empty";

// ---------- Rust ----------
function rustTy(t: Ty): string {
  if (isRef(t)) return t.ref;
  if (isArr(t)) return `Vec<${rustTy(t.array)}>`;
  switch (t) {
    case "string": return "String";
    case "integer": return "i64";
    case "number": return "f64";
    case "boolean": return "bool";
    case "freemap": return "serde_json::Value";
  }
}
function rustEnum(name: string, values: string[]): string {
  const variants = values
    .map((v) => `    #[serde(rename = "${v}")]\n    ${pascal(v)},`)
    .join("\n");
  return `#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\npub enum ${name} {\n${variants}\n}`;
}
function rustStruct(name: string, def: any): string {
  const required: string[] = def.required ?? [];
  const fields = Object.entries(def.properties ?? {})
    .map(([key, prop]) => {
      const opt = !required.includes(key);
      const ty = rustTy(mapType(prop));
      if (opt) {
        return `    #[serde(skip_serializing_if = "Option::is_none")]\n    pub ${key}: Option<${ty}>,`;
      }
      return `    pub ${key}: ${ty},`;
    })
    .join("\n");
  const derives = "#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]";
  return `${derives}\npub struct ${name} {\n${fields}\n}`;
}
function genRust(): string {
  const parts: string[] = [];
  for (const [name, def] of Object.entries(defs)) {
    if (Array.isArray(def.enum)) parts.push(rustEnum(name, def.enum));
    else parts.push(rustStruct(name, def));
  }
  return `${BANNER}\n#![allow(clippy::all)]\n\nuse serde::{Deserialize, Serialize};\n\n${parts.join("\n\n")}\n`;
}

// ---------- Swift ----------
function swiftTy(t: Ty): string {
  if (isRef(t)) return t.ref;
  if (isArr(t)) return `[${swiftTy(t.array)}]`;
  switch (t) {
    case "string": return "String";
    case "integer": return "Int";
    case "number": return "Double";
    case "boolean": return "Bool";
    case "freemap": return "AnyCodable";
  }
}
function swiftEnum(name: string, values: string[]): string {
  const cases = values.map((v) => `    case ${pascal(v)[0].toLowerCase() + pascal(v).slice(1)} = "${v}"`).join("\n");
  return `public enum ${name}: String, Codable, Sendable {\n${cases}\n}`;
}
function swiftStruct(name: string, def: any): string {
  const required: string[] = def.required ?? [];
  const props: string[] = [];
  const keys: string[] = [];
  for (const [key, prop] of Object.entries(def.properties ?? {})) {
    const opt = !required.includes(key);
    const camel = snakeToCamel(key);
    props.push(`    public var ${camel}: ${swiftTy(mapType(prop))}${opt ? "?" : ""}`);
    keys.push(`        case ${camel} = "${key}"`);
  }
  const init = `    public init(${Object.keys(def.properties ?? {})
    .map((k, i) => {
      const opt = !required.includes(k);
      return `${snakeToCamel(k)}: ${swiftTy(mapType((def.properties ?? {})[k]))}${opt ? "? = nil" : ""}`;
    })
    .join(", ")}) {\n${Object.keys(def.properties ?? {})
    .map((k) => `        self.${snakeToCamel(k)} = ${snakeToCamel(k)}`)
    .join("\n")}\n    }`;
  const codingKeys = `\n\n    enum CodingKeys: String, CodingKey {\n${keys.join("\n")}\n    }`;
  return `public struct ${name}: Codable, Sendable {\n${props.join("\n")}\n\n${init}${codingKeys}\n}`;
}
function genSwift(): string {
  const parts: string[] = [];
  for (const [name, def] of Object.entries(defs)) {
    if (Array.isArray(def.enum)) parts.push(swiftEnum(name, def.enum));
    else parts.push(swiftStruct(name, def));
  }
  return `${BANNER}\n\nimport Foundation\n\n${parts.join("\n\n")}\n`;
}

// ---------- TypeScript ----------
function tsTy(t: Ty): string {
  if (isRef(t)) return t.ref;
  if (isArr(t)) return `${tsTy(t.array)}[]`;
  switch (t) {
    case "string": return "string";
    case "integer":
    case "number": return "number";
    case "boolean": return "boolean";
    case "freemap": return "Record<string, unknown>";
  }
}
function genTs(): string {
  const parts: string[] = [];
  for (const [name, def] of Object.entries(defs)) {
    if (Array.isArray(def.enum)) {
      parts.push(`export type ${name} = ${def.enum.map((v: string) => `"${v}"`).join(" | ")}`);
    } else {
      const required: string[] = def.required ?? [];
      const fields = Object.entries(def.properties ?? {})
        .map(([key, prop]) => `  ${key}${required.includes(key) ? "" : "?"}: ${tsTy(mapType(prop))}`)
        .join("\n");
      parts.push(`export interface ${name} {\n${fields}\n}`);
    }
  }
  return `${BANNER}\n\n${parts.join("\n\n")}\n`;
}

function emit(rel: string, content: string) {
  const path = join(ROOT, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`  ✓ ${rel}`);
}

console.log("MTP codegen →");
emit("cli/crates/mtp/src/types.rs", genRust());
emit("macos/MiaottyKit/Sources/MiaottyKit/MTP/Types.swift", genSwift());
emit("plugin/src/protocol.ts", genTs());
console.log("done.");
