// @generated by proto/codegen.ts from proto/mtp.schema.json — DO NOT EDIT.

export interface ProtoRange {
  min: number
  max: number
}

export type Role = "host" | "client" | "provider" | "agent"

export type Capability = "core.basic" | "terminal.control" | "terminal.io" | "terminal.context.read" | "terminal.context.write" | "agent.state.read" | "agent.state.write" | "session.bind" | "action.invoke" | "attention.notify" | "ui.host" | "provider.quickOpen" | "provider.detailsView" | "provider.badge" | "provider.action"

export interface Limits {
  max_message_bytes: number
  rate_per_sec: number
  idle_timeout_ms: number
}

export interface HelloParams {
  proto: ProtoRange
  app_version: string
  roles: Role[]
  caps: Capability[]
  client_id: string
}

export interface WelcomeParams {
  proto: number
  session: string
  caps: Capability[]
  limits: Limits
  revision: number
}

export interface ErrorInfo {
  code: string
  message: string
  retryable: boolean
  details?: Record<string, unknown>
}

export interface Request {
  v: number
  id: number
  kind: string
  ns: string
  method: string
  params?: Record<string, unknown>
  role?: Role
  caps?: Capability[]
  ts?: number
  trace?: string
}

export interface Response {
  v: number
  id: number
  kind: string
  ok: boolean
  result?: Record<string, unknown>
  error?: ErrorInfo
  revision?: number
}

export interface Event {
  v: number
  kind: string
  ns: string
  event: string
  data?: Record<string, unknown>
  seq?: number
  replayable?: boolean
}

export type AgentState = "processing" | "idle" | "awaiting" | "error"

export interface AgentStateSetParams {
  agent: string
  session_id?: string
  pane_id?: string
  tty?: string
  agent_pid?: number
  state: AgentState
  cwd?: string
  bypass?: boolean
  error_kind?: string
  title?: string
  ts?: number
}

export interface AgentStateInfo {
  agent: string
  session_id?: string
  pane_id?: string
  state: AgentState
  cwd?: string
  bypass?: boolean
  error_kind?: string
  title?: string
  ts?: number
  seq?: number
}

export interface AgentStateListResult {
  revision: number
  states: AgentStateInfo[]
}

export interface PingResult {
  proto: number
  app_version: string
  pid: number
  caps: Capability[]
}

export interface HealthResult {
  ok: boolean
  revision: number
  connections?: number
  events_per_sec?: number
  dropped_events?: number
}

export interface Selection {
  text: string
  start_line?: number
  end_line?: number
}

export interface GitInfo {
  branch: string
  dirty: boolean
  worktree?: string
}

export interface OpenFile {
  path: string
  line?: number
  readonly?: boolean
}

export interface ContextSnapshot {
  pane_id: string
  cwd?: string
  shell?: string
  title?: string
  running?: string
  selection?: Selection
  screen_tail?: string
  scrollback_tail?: string
  git?: GitInfo
  open_file?: OpenFile
  agent?: AgentStateInfo
}

export interface ActionInfo {
  id: string
  title: string
  namespace?: string
}

export interface ActionInvokeParams {
  id: string
  args?: Record<string, unknown>
  pane_id?: string
}
